name: "Triage"

on:
  issue_comment:
    types:
      - created
      - edited

jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - name: take an issue
        uses: blackgirlbytes/take-action@add-a-comment
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          message: Thanks for taking this on! If you have not already, join the conversation in our [Discord](https://discord.gg/U2peSNf23P)